{
  "openapi": "3.0.3",
  "info": {
    "description": "You can use Admin API to create and manage your Human API users",
    "version": "1.0.0",
    "title": "Admin API",
    "termsOfService": "https://www.humanapi.co/developer-terms",
    "contact": {
      "email": "help@humanapi.co",
      "url": "https://www.humanapi.co/contact"
    }
  },
  "servers": [
    {
      "url": "https://admin.humanapi.co",
      "description": "Production server"
    }
  ],
  "tags": [
    {
      "name": "users",
      "description": "API endpoints to manage users",
      "externalDocs": {
        "description": "Find out more",
        "url": "https://reference.humanapi.co/docs/admin-api"
      }
    }
  ],
  "paths": {
    "/api/v1/users/providers": {
      "get": {
        "tags": [
          "users"
        ],
        "description": "Retrieve the list of providers for a given user",
        "operationId": "userProviders",
        "parameters": [
          {
            "$ref": "#/components/parameters/humanIdQueryOptional"
          },
          {
            "$ref": "#/components/parameters/clientUserIdQueryOptional"
          }
        ],
        "responses": {
          "200": {
            "description": "Accepted",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/providersResponse"
                }
              }
            }
          },
          "400": {
            "$ref": "#/components/responses/badRequest"
          },
          "401": {
            "$ref": "#/components/responses/unauthorized"
          },
          "404": {
            "$ref": "#/components/responses/notFound"
          }
        }
      }
    }
  },
  "components": {
    "securitySchemes": {
      "bearerAuth": {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT"
      }
    },
    "schemas": {
      "providersResponse": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "id": {
              "type": "string"
            },
            "name": {
              "type": "string"
            }
          }
        }
      },
      "error": {
        "type": "object",
        "required": [
          "statusCode",
          "error",
          "message",
          "x-humanapi-request-id"
        ],
        "properties": {
          "code": {
            "type": "integer",
            "format": "int32"
          },
          "error": {
            "type": "string"
          },
          "message": {
            "type": "string"
          },
          "x-humanapi-request-id": {
            "type": "string"
          }
        }
      }
    },
    "parameters": {
      "humanIdQueryOptional": {
        "name": "humanId",
        "in": "query",
        "description": "The humanId of the user",
        "required": false,
        "schema": {
          "type": "string"
        }
      },
      "clientUserIdQueryOptional": {
        "name": "clientUserId",
        "in": "query",
        "description": "The clientUserId that the subscription is listening to",
        "required": false,
        "schema": {
          "type": "string"
        }
      }
    },
    "responses": {
      "badRequest": {
        "description": "Cannot process input data",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/error"
            },
            "example": {
              "code": 400,
              "error": "Bad Request",
              "message": "Bad Request",
              "x-humanapi-request-id": "05518ca2-1c9a-434e-8512-7284bbc54137"
            }
          }
        }
      },
      "unauthorized": {
        "description": "The token provided is invalid. It may have expired or may have been revoked.",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/error"
            },
            "example": {
              "code": 401,
              "error": "Unauthorized",
              "message": "Cannot authenticate you with this token",
              "x-humanapi-request-id": "05518ca2-1c9a-434e-8512-7284bbc54137"
            }
          }
        }
      },
      "notFound": {
        "description": "The specified resource was not found (e.g. the id does not exist)",
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/error"
            },
            "example": {
              "code": 404,
              "error": "Not Found",
              "message": "Not Found",
              "x-humanapi-request-id": "05518ca2-1c9a-434e-8512-7284bbc54137"
            }
          }
        }
      }
    }
  },
  "security": [
    {
      "bearerAuth": []
    }
  ],
  "x-readme": {
    "explorer-enabled": true,
    "proxy-enabled": true
  }
}